resources:
  - ../../../base/postgres/auth-db
  - ../../../base/postgres/product-db
  - ../../../base/postgres/order-db

patches:
  - path: auth-db-patch.yaml
  - path: product-db-patch.yaml
  - path: order-db-patch.yaml

secretGenerator:
- name: auth-db-secret
  literals:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=auth

- name: order-db-secret
  literals:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=order

- name: product-db-secret
  literals:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=product