apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: product-db
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: product-db
  serviceName: "product-db-service"
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: product-db
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k3d-cluster-agent-0
                - k3d-cluster-agent-1
      terminationGracePeriodSeconds: 10
      containers:
        - name: product-db
          image: postgres
          ports:
            - containerPort: 5432
              name: postgres
              
          envFrom:
            - secretRef:
                name: product-db-secret
                
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "user", "--dbname=product"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "user", "--dbname=product"]
            initialDelaySeconds: 15
            periodSeconds: 20

          volumeMounts:
            - name: product-db
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: product-db
      spec:
        storageClassName: local-path-retain
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
