apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq         
spec:
  revisionHistoryLimit: 2
  serviceName: "rabbitmq-service"   
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq
          ports:
            - containerPort: 5672            
              name: amqp
            - containerPort: 15672           
              name: http
          envFrom:
            - secretRef:
                name: rabbitmq-secret

          volumeMounts:
            - name: rabbit-data              
              mountPath: /var/lib/rabbitmq    
            - name: rabbit-log              
              mountPath: /var/log/rabbitmq    

  volumeClaimTemplates:
    - metadata:
        name: rabbit-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi                     
    - metadata:
        name: rabbit-log
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi           