apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq         
spec:
  revisionHistoryLimit: 2
  serviceName: "rabbitmq-service"   
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k3d-cluster-agent-0
                - k3d-cluster-agent-1
      containers:
        - name: rabbitmq
          image: rabbitmq
          ports:
            - containerPort: 5672            
              name: amqp
            - containerPort: 15672           
              name: http
            - containerPort: 15692
              name: prometheus
          envFrom:
            - secretRef:
                name: rabbitmq-secret
          env:
            - name: RABBITMQ_PLUGINS
              value: "rabbitmq_prometheus"
          volumeMounts:
            - name: rabbit-data              
              mountPath: /var/lib/rabbitmq    
            - name: rabbit-log              
              mountPath: /var/log/rabbitmq    

  volumeClaimTemplates:
    - metadata:
        name: rabbit-data
      spec:
        storageClassName: local-path-retain
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi                     
    - metadata:
        name: rabbit-log
      spec:
        storageClassName: local-path-retain
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi           