resources:
  - ../../../../base/product

patches:
  - path: patch.yaml

secretGenerator:
- name: product-secret
  literals:
    - POSTGRES_HOST=product-db-service
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=product
    - RABBITMQ_PRODUCT_QUEUE=product
    - RABBITMQ_ORDER_QUEUE=order
    - RABBITMQ_URL=amqp://rabbitmq-service:5672