apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: auth-db
  serviceName: "auth-db-service"
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: auth-db
          image: postgres
          ports:
            - containerPort: 5432
              name: postgres

          envFrom:
            - secretRef:
                name: auth-db-secret

          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "user", "--dbname=auth"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "user", "--dbname=auth"]
            initialDelaySeconds: 15
            periodSeconds: 20

          volumeMounts:
            - name: auth-db
              mountPath: /var/lib/postgresql
  volumeClaimTemplates:
    - metadata:
        name: auth-db
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
