resources:
  - ../../../../base/api-gateway
  
patches:
  - path: patch.yaml

secretGenerator:
- name: api-gateway-secret
  literals:
    - AUTH_URL=http://auth-service:5001
    - PRODUCT_URL=http://product-service:5002
    - ORDER_URL=http://order-service:5003