apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-db-application # The name of the Argo CD Application resource
  namespace: argocd # The namespace where Argo CD is installed
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: ecommerce-project-dev # The Argo CD project the application belongs to
  destination:
    server: https://kubernetes.default.svc # The target Kubernetes cluster API server
    namespace: ecommerce-dev # The target namespace for deployment
  source:
    repoURL: https://github.com/ebad-arshad/aws-devops-gitops-platform # The Git repository URL
    targetRevision: master # The branch/tag/commit to sync from
    path: k8s/overlays/dev/db/product-db-patch # The path within the repo containing Kubernetes manifests
  syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true